coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - longtests
flags:
  ubuntutests:
    joined: false
  wintests:
    joined: false